
name: Demo
on:
  
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: robinraju/release-downloader@v1
        with:
          repository: '2dust/v2rayN'
          tag: '7.20.4'
          fileName: 'v2rayN-windows-64-desktop.zip'
      - name: Upload
        if: always()
        uses: actions/upload-artifact@v4

